#!/usr/bin/python3
import json 

with open("mapa-virtual.json") as f :
    mapaVirtual = json.load(f)
    cidades = mapaVirtual['cidades']
    ligacoes = mapaVirtual['ligações']
    with open ("mapa-virtual.ttl","w") as file:

        file.write("""
@prefix : <http://www.di.uminho.pt/prc2021/mapaVirtual#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.di.uminho.pt/prc2021/mapaVirtual> .

<http://www.di.uminho.pt/prc2021/mapaVirtual> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://www.di.uminho.pt/prc2021/mapaVirtual#temDestino
:temDestino rdf:type owl:ObjectProperty ;
            rdfs:domain :ligação ;
            rdfs:range :cidade .


###  http://www.di.uminho.pt/prc2021/mapaVirtual#temOrigem
:temOrigem rdf:type owl:ObjectProperty ;
           rdfs:domain :ligação ;
           rdfs:range :cidade .


#################################################################
#    Data properties
#################################################################

###  http://www.di.uminho.pt/prc2021/mapaVirtual#descrição
:descrição rdf:type owl:DatatypeProperty .


###  http://www.di.uminho.pt/prc2021/mapaVirtual#distrito
:distrito rdf:type owl:DatatypeProperty .


###  http://www.di.uminho.pt/prc2021/mapaVirtual#distância
:distância rdf:type owl:DatatypeProperty .


###  http://www.di.uminho.pt/prc2021/mapaVirtual#nome
:nome rdf:type owl:DatatypeProperty .


###  http://www.di.uminho.pt/prc2021/mapaVirtual#população
:população rdf:type owl:DatatypeProperty .


#################################################################
#    Classes
#################################################################

###  http://www.di.uminho.pt/prc2021/mapaVirtual#cidade
:cidade rdf:type owl:Class .


###  http://www.di.uminho.pt/prc2021/mapaVirtual#ligação
:ligação rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################

""")

        for c in cidades :
           file.write("""
        ###  http://www.di.uminho.pt/prc2021/mapaVirtual#{id}
        :{id} rdf:type owl:NamedIndividual ,
                     :cidade ;
            :nome "{nome}"^^xsd:string ;
            :distrito "{distrito}"^^xsd:string ;
            :população "{populacao}"^^xsd:int ;
            :descrição "{descricao}"^^xsd:string .
""".format(id=c['id'],descricao=c['descrição'],distrito=c['distrito'],nome=c['nome'],populacao=c['população'])
)
        for l in ligacoes : 
            file.write("""
        ###  http://www.di.uminho.pt/prc2021/mapaVirtual#{id}
        :{id} rdf:type owl:NamedIndividual ,
        :ligação ;
        :temOrigem :{origem} ;
        :temDestino :{destino} ;
        :distância "{distancia}"^^xsd:double .
""".format(id=l['id'],origem=l['origem'],destino=l['destino'],distancia=l['distância'])
            )
        file.write("###  Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi")